global:
  message: Welcome to globar microservice environment
loggin:
  level:
    roo: INFO
eureka:
  client:
    service-url:
      defaltZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
