global:
  message: Welcome to globar microservice environment
loggin:
  level:
    roo: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
