global:
  message: Welcome to cusotmer prod microservice environment
server:
  port: 8082
message: hello from customer service demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user    # Must match the MYSQL_USER in your docker-compose.yml
    password: password # Must match the MYSQL_PASSWORD in your docker-compose.yml
    driver-class-name: com.mysql.cj.jdbc.Driver # The JDBC driver class for MySQL

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Log SQL queries to console (useful for debugging)
    properties:
      hibernate:
        format_sql: true # Format SQL logs for readability
